ballerina-platform/blog

docs/posts/post_0004.md
> Fix code syntax highlighting issue
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
=> Fix code syntax highlighting issue

docs/index.md, mkdocs.yml
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …
=> Change home page to index.md

docs/blog_summary.py
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …
=> Sort meta data by date

ballerina.io-blog-theme/base.html, docs/blog_summary.py, docs/posts/introducting-native-programming.md, docs/posts/next-geneation-integration.md, docs/posts/post_0001.md, docs/posts/post_0002.md, docs/posts/post_0003.md, docs/posts/post_0004.md, docs/posts/quick-tour with-ballerina.md, docs/posts/thinking-in-ballerina.md
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …
=> Update the featured image url

docs/posts/ballerina-meets-hasura.md
Added a couple headings that will show up in the TOC.
=> Add headings to blog post

docs/index.md, docs/posts/ballerina-a-cloud-native-programming-language.md, docs/posts/introduction-to-ballerina-0.970.md
Reverts ballerina-platform/blog#21
=> Revert "Update the blogs index page"

docs/posts/overview-of-ballerina-0.980.md
Fixes some source code formatting issues.
=> Fix code formatting issue

docs/posts/overview-of-ballerina-0.982.0.md
Update the date for the 0.982.0 blog
=> Update the date for the 0.982.0 blog

ballerina.io-blog-theme/base.html, ballerina.io-blog-theme/js/ballerina-common.js
Fix the link to Ballerina Lang's twitter account (looks like it used to be ballerinaplat, and is now ballerinalang).
=> Correct Twitter handle on blog

_includes/nav.html
Add the Playground option to the top menu.
=> Add the Playground Option to the Top Menu

_includes/nav.html
Remove Events from the top menu.
=> Remove Events from the Top Menu

css/ballerina-blog.css
Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/2172
=> Change navigation link colors

_includes/footer.html, _includes/nav.html
Improve the footer links and top menu items.
=> Improve Footer Links and Top Menu Items

_includes/footer.html, _includes/nav-breadcrumbs.html, _layouts/blog-home.html, _layouts/blog-post.html
Improve blog links and styles.
=> Improve Blog Links and Styles

_includes/footer.html
=> Revert the Newsletter Button

_includes/footer.html, _includes/nav.html, _layouts/blog-home.html, _layouts/blog-post.html, _site/css/ballerina-blog.css
##Purpose
> Fix following issues
> Fixes #2460
> Fixes #2461
> Fixes #2472
> Fixes #2465
> Fixes #2466
=> Update Footer Content, Add Search Bar and Add Breadcrumbs 

_includes/footer.html
Fix the link of the newsletter footer button.
=> Fix the Link of the Newsletter Footer Button

_includes/nav-breadcrumbs.html
=> Add Working Breadcrumbs

_posts/2018-06-04-introduction-to-ballerina-0.970.md, _posts/2018-06-26-improvements-and-new-features-in-ballerina-0.980.0-release.md, _posts/2018-10-08-introduction-to-new-features-and-changes-introduced-with-ballerina-0.982.0.md, _posts/2019-09-09-annoucing-1.0.0.md, _posts/2020-01-02-ballerina-1.1.0-released.md, _posts/2020-03-20-ballerina-1.2.0-released.md, _posts/2020-06-19-announcing-the-first-preview-of-ballerina-swan-lake.md, _posts/2021-06-02-announcing-ballerina-swan-lake-beta1.md
Reverts ballerina-platform/blog#88
=> Revert "Remove the Descriptions of the Announcement Blogs"

index.md
=> Remove the Blog Descriptions

_posts/2021-12-14-ballerina-swan-lake-is-on-the-horizon.md
=> Update the SLBeta6 Blog

_posts/2021-12-14-ballerina-swan-lake-is-on-the-horizon.md
=> Fix Formatting

_posts/2021-12-14-ballerina-swan-lake-is-on-the-horizon.md
=> Fix Indentation

_posts/2021-12-23-ballerina-log4shell-vulnerability-community-update.md
Add the Log4Shell community update announcement
=> Add the Log4Shell Community Update Announcement

_posts/2021-12-23-ballerina-log4shell-vulnerability-community-update.md
Improve the Log4j announcement
=> Improve the Log4j Announcement

_posts/2021-12-14-ballerina-swan-lake-is-on-the-horizon.md
=> Fix the Second Update Version

_posts/2021-12-14-ballerina-swan-lake-is-on-the-horizon.md, _posts/2021-12-23-ballerina-log4shell-vulnerability-community-update.md
=> Fix footer paragraph bug

_posts/2022-02-01-announcing-ballerina-2201.0.0-swan-lake.md
Update the date of the blog post
=> Update the Date of the Blog Post

_posts/2022-02-01-announcing-ballerina-2201.0.0-swan-lake.md
=> Update the SL GA Blog

_includes/footer.html, _posts/2022-02-01-announcing-ballerina-2201.0.0-swan-lake.md
=> Fix the Community Page Link

_includes/footer.html
Update sentence case in newsletter footer button.
=> Update Sentence Case in the Newsletter Footer Button

_posts/2018-06-04-introduction-to-ballerina-0.970.md, _posts/2018-06-26-improvements-and-new-features-in-ballerina-0.980.0-release.md, _posts/2018-10-08-introduction-to-new-features-and-changes-introduced-with-ballerina-0.982.0.md, _posts/2019-09-09-annoucing-1.0.0.md, _posts/2020-01-02-ballerina-1.1.0-released.md, _posts/2020-03-20-ballerina-1.2.0-released.md, _posts/2021-06-02-announcing-ballerina-swan-lake-beta1.md, _posts/2021-12-14-ballerina-swan-lake-is-on-the-horizon.md, _posts/2021-12-23-ballerina-log4shell-vulnerability-community-update.md, _posts/2022-02-01-announcing-ballerina-2201.0.0-swan-lake.md
Fix the sentence case in blogs
=> Fix the Sentence Case in Blogs

_includes/footer.html
Add the cookie policy to the footer
=> Add the Cookie Policy to the Footer

404.html
=> Update the 404 Error Page

404.html, _includes/ballerina-head.html, css/ballerina-io-learn-v2.css, css/ballerina-io.css
=> Fix the Link of the 404 Page

_includes/footer.html
Change the order of the footer icons as per https://github.com/ballerina-platform/ballerina-dev-website/issues/4005.
=> Change the Order of the Footer Icons

_includes/footer.html, img/slack-2022.svg
Update the Slack logo in the footer.
=> Update the Slack Logo in Footer

_includes/footer.html
Add LinkedIn and Google Group footer icons. …
=> Add LinkedIn and Google Group Footer Icons

_includes/footer.html, css/ballerina-blog.css
Fix the blog footer icon alignments. …
=> Fix the Blog Footer Icon Alignments

_posts/2022-05-30-announcing-ballerina-2201.1.0-swan-lake-update-1.md
Add the 2201.1.0 Swan Lake Update 1 blog. …
=> Add the 2201.1.0 Swan Lake Update 1 blog

_posts/2022-05-30-announcing-ballerina-2201.1.0-swan-lake-update-1.md
Update the release note link in 2201.1.0 blog. …
=> Update the Release Note Link in the 2201.1.0 Blog

_includes/nav.html
=> Fix broken links

_includes/footer.html, css/ballerina-io.css
=> Update footer to match b.io

_layouts/blog-home.html, _layouts/blog-post.html
=> Remove breadcrumbs from blogs

_layouts/blog-post.html
=> Add back to blogs button

_layouts/blog-home.html
=> Update blog home page title

_includes/footer.html
=> Add new discord url

_includes/algolia-open-source.html
=> Update the search index

_layouts/blog-home.html, _layouts/blog-post.html, css/ballerina-blog.css
=> Add hackathon banner

_posts/2022-08-10-announcing-ballerina-2201.2.0-swan-lake-update-2.md
Add the Swan Lake 2201.2.0 announcement blog. …
=> Add the Swan Lake 2201.2.0 announcement blog

_posts/2022-08-10-announcing-ballerina-2201.2.0-swan-lake-update-2.md, css/ballerina-blog.css
=> Fix styling issues

_posts/2022-09-21-ballerina-is-moving-from-slack-to-discord.md
=> Add new blog post

_layouts/blog-home.html, _layouts/blog-post.html
=> Remove Hackathon banner from blog

_layouts/blog-home.html, _layouts/blog-post.html
=> Remove commented code

_includes/footer.html
=> Add tooltips to icons

_includes/footer.html
=> Update Discord URL

_posts/2022-12-05-announcing-ballerina-2201.3.0-swan-lake-update-3.md
Add the 2201.3.0 announcement blog. …
=> Add the 2201.3.0 announcement blog

_includes/algolia-open-source.html
> $subject
> Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/6286
> Type “Sent” when you have …
=> Update Algolia search index

_posts/2023-02-28-announcing-ballerina-2201.4.0-swan-lake-update-4.md
Remove extra lines in Update 4 blog. …
=> Remove extra lines in Update 4 blog

_includes/nav.html, css/ballerina-blog.css
=> Add Use cases to top nav

_includes/footer.html
Add copyright to footer.
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if …
=> Add copyright to footer

_includes/ballerina-head.html, _includes/footer.html, css/prism.css, js/prism-ballerina.js, js/prism.js
> $subject
Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/6419
> Link to the PR for changes to the …
=> Add syntax highlighting to blogs

_includes/algolia-open-source.html
=> Add new search api key

_includes/algolia-open-source.html
=> Update Algolia keys

pages/index.js
=> Fix hydration issue

utils/generateRSSFeed.js
=> Update self reference in rss feed

.github/workflows/prod_sync.yml, components/common/footer/Footer.js, utils/rearrangeFiles.sh
> $subject
Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/6885
> Link to the PR for changes to the …
=> Fix 404 page and Remove Google Groups from footer

components/common/top-nav/TopNav.js
=> Add Healthcare link to Top nav

_posts/2023-05-31-announcing-ballerina-2201.6.0-swan-lake-update-6.md
Add the Update 6 blog.
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if …
=> Add the Update 6 blog

_posts/2023-06-06-announcing-ballerina-2201.6.0-swan-lake-update-6.md
Do minor improvements to the Update 6 blog. …
=> Do minor improvements to the Update 6 blog

_posts/2023-06-06-announcing-ballerina-2201.6.0-swan-lake-update-6.md
Fix syntax highlighting of the persist example. …
=> Fix syntax highlighting of the persist example

_posts/2023-07-14-announcing-ballerina-2201.7.0-swan-lake-update-7.md
Change the date of the Up7 blog.
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, …
=> Change the date of the Up7 blog

components/common/top-nav/CustomMenu.js, components/common/top-nav/CustomToggle.js, components/common/top-nav/TopNav.js, components/common/top-nav/TopNav.module.css, package-lock.json, package.json
=> Update Top nav in Blog

components/common/top-nav/TopNav.js
=> Update Top Nav

components/common/top-nav/TopNav.js
=> Remove playground from topNav

components/common/footer/Footer.js
Fix the footer hyperlinks.
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if …
=> Fix the footer hyperlinks

components/common/footer/Footer.js, public/js/api-doc-template.js
=> Fix broken hyperlinks

components/common/footer/Footer.js
=> Update copyright message

components/common/top-nav/TopNav.js, components/common/top-nav/TopNav.module.css
=> Add hacktoberfest banner

components/common/footer/Footer.js
=> Update linkedin url

pages/404.js, pages/index.js, pages/posts/[slug].js
=> Remove duplicated h1 and title tags

components/common/top-nav/TopNav.js, pages/index.js
=> Update topNav and fix build errors

components/common/top-nav/TopNav.js
=> Add fat-tuesday to top nav

components/common/top-nav/TopNav.js
=> Add Qhana to top nav

components/common/top-nav/TopNav.js
=> Add ETL to top nav

components/common/top-nav/TopNav.js, components/common/top-nav/TopNav.module.css
=> Add WSO2Con banner

components/common/top-nav/TopNav.module.css
=> Add onHover styles to WSO2Con banner

components/common/footer/Footer.js, components/common/footer/Footer.module.css, package-lock.json, package.json, pages/_app.js
=> Update 3rd party logos in the footer

components/common/footer/Footer.js, layouts/Layout404.js, layouts/LayoutDocs.js, layouts/LayoutHome.js
=> Dynamically update the copyright year

pages/index.js, pages/posts/[slug].js
=> Render html tags within the title

_posts/2025-04-26-introducing-natural-programming.md
=> Remove HTML in title

_posts/2025-04-26-introducing-natural-programming.md, pages/posts/[slug].js
> $subject
Removed the HTML tags and other special characters to avoid SEO issues
> Link to the PR for changes to the training …
=> Remove html tags from page title
